domains:
    - cs.LG
    - stat.ML
keywords:
    - (all:graph) AND (all:unsupervised OR all:self-supervised OR all:representation learning OR all:convolutional networks)
    - (all:graph) AND (all:recommendation OR all:recommender OR all:sequential)
query_config:
    sort_by: LastUpdatedDate
    sort_order: Descending
    max_results: 10
mail:
    user: example@server.com
    server: smtp.server.com
    port: 465
    password: password
    recipient:
        - me@hello.com
